name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-24.04
    outputs:
      registry: ${{ steps.info.outputs.registry }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Info
        id: info
        run: echo "registry=${{ env.REGISTRY }}" >> $GITHUB_OUTPUT

      - name: Log in to registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Normalize repo owner
        id: repo_owner
        uses: ./.github/actions/to-lower
        with:
          string: ${{ github.repository_owner }}

      - name: Build and Push all targets
        uses: docker/bake-action@a66e1c87e2eca0503c343edf1d208c716d54b8a8 # v7
        env:
          REPO_OWNER: ${{ steps.repo_owner.outputs.lower-case }}
          REGISTRY: ${{ env.REGISTRY }}
          TAG: sha-${{ github.sha }}
        with:
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  smoke-test:
    name: Run Smoke Test
    needs: build
    uses: ./.github/workflows/lib.smoke-test.yml
    with:
      registry: ${{ needs.build.outputs.registry }}